import { uglify } from "rollup-plugin-uglify"
import resolve from "@rollup/plugin-node-resolve"
import pkg from "./package.json"

const banner = `
/*!
 * ${pkg.name}-core ${pkg.version} (${pkg.homepage})
 * Copyright 2022-${new Date().getFullYear()} ${pkg.author}
 * Licensed under ${pkg.license}
 *
 * This file is automatically generated, please do not change it.
 */
`.trim()

export default [
    {
        input: "./src/core/util/common.js",
        output: {
            strict: true,
            name: `${pkg.name}-core`,
            banner,
            sourcemap: true,
            format: "es",
            file: "./public/js/lib/util.min.js"
        },
        plugins: [
            resolve(),
            uglify({
                output: {
                    preamble: banner
                }
            })
       ]
    },
    {
        input: "./src/core/util/JSONWithFun.js",
        output: {
            strict: true,
            name: `${pkg.name}-core`,
            banner,
            sourcemap: true,
            format: "es",
            file: "./public/js/lib/JSONWithFun.min.js"
        },
        plugins: [
            resolve(),
            uglify({
                output: {
                    preamble: banner
                }
            })
       ]
    },
    {
        input: "./src/core/index.js",
        output: {
            strict: true,
            name: "mcbece-core",
            banner,
            sourcemap: true,
            format: "es",
            file: "./public/js/lib/core.min.js"
        },
        plugins: [
            resolve(),
            uglify({
                output: {
                    preamble: banner
                }
            })
       ]
    }
]
