import { nodeResolve } from "@rollup/plugin-node-resolve"
import commonjs from "@rollup/plugin-commonjs"
import { uglify } from "rollup-plugin-uglify"
import pkg from "./package.json"

const banner = `
/*!
 * ${pkg.name}-core.js v${pkg.version} (${pkg.homepage})
 * Copyright 2022-${new Date().getFullYear()} ${pkg.author}
 * Licensed under ${pkg.license}
 *
 * This file is automatically generated, please do not change it.
 */
`.trim()

export default [
    // utils
    _({
        src: "core/util/common.js",
        dest: "lib/util.min.js",
        name: "util"
    }),
    _({
        src: "core/util/betterJSON.js",
        dest: "lib/betterJSON.min.js",
        name: "util"
    }),
    
    // core
    _({
        src: "core/index.js",
        dest: "lib/core.min.js",
        name: "core"
    }),
    
    // bundle.js
    _({
        src: "index.js",
        dest: "bundle.min.js",
        mame: "bundle"
    }),
    
    // custom file
    _({
        src: "data/example.js",
        dest: "custom/example.min.js",
        name: "custom-file"
    }),
    _({
        src: "data/dev.js",
        dest: "custom/dev.min.js",
        name: "custom-file"
    })
]

function _({ src, dest, name }) {
    return {
        input: `./src/browser/js/${src}`,
        output: {
            strict: true,
            name: `${pkg.name}${ name ? `-${name}` : "" }.js`,
            banner,
            sourcemap: true,
            format: "es",
            file: `./public/js/${dest}`
        },
        plugins: [
            nodeResolve({
                preferBuiltins: false
            }),
            commonjs(),
            uglify({
                output: {
                    preamble: banner
                }
            })
        ]
    }
}
